"""phase4_workflow_and_evidence_schema

Revision ID: 008
Revises: 007
Create Date: 2026-07-26 20:56:58.768721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008'
down_revision: Union[str, Sequence[str], None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('int_BackgroundJob',
    sa.Column('JobID', sa.String(length=50), nullable=False),
    sa.Column('JobType', sa.String(length=100), nullable=False),
    sa.Column('Payload', sa.Text(), nullable=True),
    sa.Column('IdempotencyKey', sa.String(length=100), nullable=True),
    sa.Column('RequestedByUserID', sa.Integer(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('AttemptCount', sa.Integer(), nullable=True),
    sa.Column('MaxAttempts', sa.Integer(), nullable=True),
    sa.Column('ResultRef', sa.String(length=500), nullable=True),
    sa.Column('ErrorMessage', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('StartedAt', sa.DateTime(), nullable=True),
    sa.Column('CompletedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['RequestedByUserID'], ['auth_User.UserID'], ),
    sa.PrimaryKeyConstraint('JobID')
    )
    op.create_index(op.f('ix_int_BackgroundJob_IdempotencyKey'), 'int_BackgroundJob', ['IdempotencyKey'], unique=True)
    op.create_table('int_ReportRequest',
    sa.Column('ReportID', sa.String(length=50), nullable=False),
    sa.Column('RequestedByUserID', sa.Integer(), nullable=False),
    sa.Column('ReportType', sa.String(length=50), nullable=False),
    sa.Column('Parameters', sa.Text(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('StorageObjectRef', sa.String(length=500), nullable=True),
    sa.Column('FileFormat', sa.String(length=20), nullable=True),
    sa.Column('ErrorMessage', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('CompletedAt', sa.DateTime(), nullable=True),
    sa.Column('ExpiresAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['RequestedByUserID'], ['auth_User.UserID'], ),
    sa.PrimaryKeyConstraint('ReportID')
    )
    op.create_index(op.f('ix_int_ReportRequest_RequestedByUserID'), 'int_ReportRequest', ['RequestedByUserID'], unique=False)
    op.create_table('int_CaseAssignment',
    sa.Column('AssignmentID', sa.Integer(), nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=False),
    sa.Column('AssignedOfficerID', sa.Integer(), nullable=False),
    sa.Column('AssignedByUserID', sa.Integer(), nullable=False),
    sa.Column('AssignmentReason', sa.String(length=500), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('AssignedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('EndedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['AssignedByUserID'], ['auth_User.UserID'], ),
    sa.ForeignKeyConstraint(['AssignedOfficerID'], ['src_Employee.EmployeeID'], ),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['src_CaseMaster.CaseMasterID'], ),
    sa.PrimaryKeyConstraint('AssignmentID')
    )
    op.create_index(op.f('ix_int_CaseAssignment_AssignedOfficerID'), 'int_CaseAssignment', ['AssignedOfficerID'], unique=False)
    op.create_index(op.f('ix_int_CaseAssignment_CaseMasterID'), 'int_CaseAssignment', ['CaseMasterID'], unique=False)
    op.create_table('int_InvestigationNote',
    sa.Column('NoteID', sa.Integer(), nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=False),
    sa.Column('AuthorID', sa.Integer(), nullable=False),
    sa.Column('NoteType', sa.String(length=50), nullable=True),
    sa.Column('Content', sa.Text(), nullable=False),
    sa.Column('IsAmendment', sa.Boolean(), nullable=True),
    sa.Column('OriginalNoteID', sa.Integer(), nullable=True),
    sa.Column('Visibility', sa.String(length=50), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['AuthorID'], ['auth_User.UserID'], ),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['src_CaseMaster.CaseMasterID'], ),
    sa.ForeignKeyConstraint(['OriginalNoteID'], ['int_InvestigationNote.NoteID'], ),
    sa.PrimaryKeyConstraint('NoteID')
    )
    op.create_index(op.f('ix_int_InvestigationNote_CaseMasterID'), 'int_InvestigationNote', ['CaseMasterID'], unique=False)
    op.create_table('int_RelatedCaseSuggestion',
    sa.Column('SuggestionID', sa.Integer(), nullable=False),
    sa.Column('SourceFIRID', sa.Integer(), nullable=False),
    sa.Column('CandidateFIRID', sa.Integer(), nullable=False),
    sa.Column('ConfidenceScore', sa.Float(), nullable=False),
    sa.Column('SupportingSignals', sa.Text(), nullable=False),
    sa.Column('Explanation', sa.Text(), nullable=False),
    sa.Column('ModelVersion', sa.String(length=50), nullable=True),
    sa.Column('ReviewStatus', sa.String(length=50), nullable=True),
    sa.Column('ReviewedByUserID', sa.Integer(), nullable=True),
    sa.Column('ReviewReason', sa.String(length=500), nullable=True),
    sa.Column('ReviewedAt', sa.DateTime(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['CandidateFIRID'], ['src_CaseMaster.CaseMasterID'], ),
    sa.ForeignKeyConstraint(['ReviewedByUserID'], ['auth_User.UserID'], ),
    sa.ForeignKeyConstraint(['SourceFIRID'], ['src_CaseMaster.CaseMasterID'], ),
    sa.PrimaryKeyConstraint('SuggestionID')
    )
    op.create_index(op.f('ix_int_RelatedCaseSuggestion_CandidateFIRID'), 'int_RelatedCaseSuggestion', ['CandidateFIRID'], unique=False)
    op.create_index(op.f('ix_int_RelatedCaseSuggestion_SourceFIRID'), 'int_RelatedCaseSuggestion', ['SourceFIRID'], unique=False)
    op.create_table('int_SupervisorReview',
    sa.Column('ReviewID', sa.Integer(), nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=False),
    sa.Column('SupervisorID', sa.Integer(), nullable=False),
    sa.Column('ReviewType', sa.String(length=50), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('Comments', sa.Text(), nullable=True),
    sa.Column('ActionRequested', sa.String(length=200), nullable=True),
    sa.Column('ReviewedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['src_CaseMaster.CaseMasterID'], ),
    sa.ForeignKeyConstraint(['SupervisorID'], ['auth_User.UserID'], ),
    sa.PrimaryKeyConstraint('ReviewID')
    )
    op.create_index(op.f('ix_int_SupervisorReview_CaseMasterID'), 'int_SupervisorReview', ['CaseMasterID'], unique=False)
    op.add_column('src_EvidenceMaster', sa.Column('CollectedAt', sa.DateTime(), nullable=True))
    op.add_column('src_EvidenceMaster', sa.Column('CollectedBy', sa.String(length=200), nullable=True))
    op.add_column('src_EvidenceMaster', sa.Column('Source', sa.String(length=200), nullable=True))
    op.add_column('src_EvidenceMaster', sa.Column('Location', sa.String(length=500), nullable=True))
    op.add_column('src_EvidenceMaster', sa.Column('Checksum', sa.String(length=100), nullable=True))
    op.add_column('src_EvidenceMaster', sa.Column('FileType', sa.String(length=100), nullable=True))
    op.add_column('src_EvidenceMaster', sa.Column('FileSize', sa.Integer(), nullable=True))
    op.add_column('src_EvidenceMaster', sa.Column('Status', sa.String(length=50), nullable=True))
    op.add_column('src_EvidenceMaster', sa.Column('Sensitivity', sa.String(length=50), nullable=True))
    op.add_column('src_EvidenceMaster', sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('src_EvidenceMaster', 'UpdatedAt')
    op.drop_column('src_EvidenceMaster', 'Sensitivity')
    op.drop_column('src_EvidenceMaster', 'Status')
    op.drop_column('src_EvidenceMaster', 'FileSize')
    op.drop_column('src_EvidenceMaster', 'FileType')
    op.drop_column('src_EvidenceMaster', 'Checksum')
    op.drop_column('src_EvidenceMaster', 'Location')
    op.drop_column('src_EvidenceMaster', 'Source')
    op.drop_column('src_EvidenceMaster', 'CollectedBy')
    op.drop_column('src_EvidenceMaster', 'CollectedAt')
    op.drop_index(op.f('ix_int_SupervisorReview_CaseMasterID'), table_name='int_SupervisorReview')
    op.drop_table('int_SupervisorReview')
    op.drop_index(op.f('ix_int_RelatedCaseSuggestion_SourceFIRID'), table_name='int_RelatedCaseSuggestion')
    op.drop_index(op.f('ix_int_RelatedCaseSuggestion_CandidateFIRID'), table_name='int_RelatedCaseSuggestion')
    op.drop_table('int_RelatedCaseSuggestion')
    op.drop_index(op.f('ix_int_InvestigationNote_CaseMasterID'), table_name='int_InvestigationNote')
    op.drop_table('int_InvestigationNote')
    op.drop_index(op.f('ix_int_CaseAssignment_CaseMasterID'), table_name='int_CaseAssignment')
    op.drop_index(op.f('ix_int_CaseAssignment_AssignedOfficerID'), table_name='int_CaseAssignment')
    op.drop_table('int_CaseAssignment')
    op.drop_index(op.f('ix_int_ReportRequest_RequestedByUserID'), table_name='int_ReportRequest')
    op.drop_table('int_ReportRequest')
    op.drop_index(op.f('ix_int_BackgroundJob_IdempotencyKey'), table_name='int_BackgroundJob')
    op.drop_table('int_BackgroundJob')
    # ### end Alembic commands ###
