"""phase3_p0_tables

Revision ID: edce56cd43ea
Revises: ffff29081afe
Create Date: 2026-07-26 13:20:27.200690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edce56cd43ea'
down_revision: Union[str, Sequence[str], None] = 'ffff29081afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('int_ERMergeCandidate',
    sa.Column('CandidateID', sa.Integer(), nullable=False),
    sa.Column('EntityA', sa.Integer(), nullable=False),
    sa.Column('EntityB', sa.Integer(), nullable=False),
    sa.Column('SimilarityScore', sa.Float(), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('ReviewedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['EntityA'], ['int_PersonEntity.PersonEntityID'], ),
    sa.ForeignKeyConstraint(['EntityB'], ['int_PersonEntity.PersonEntityID'], ),
    sa.ForeignKeyConstraint(['ReviewedBy'], ['auth_User.UserID'], ),
    sa.PrimaryKeyConstraint('CandidateID')
    )
    op.create_table('int_AIExtractionQueue',
    sa.Column('ExtractionID', sa.Integer(), nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('ModelUsed', sa.String(length=100), nullable=True),
    sa.Column('RawJSON', sa.Text(), nullable=True),
    sa.Column('ReviewedBy', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['src_CaseMaster.CaseMasterID'], ),
    sa.ForeignKeyConstraint(['ReviewedBy'], ['auth_User.UserID'], ),
    sa.PrimaryKeyConstraint('ExtractionID')
    )
    op.create_table('src_EvidenceMaster',
    sa.Column('EvidenceID', sa.Integer(), nullable=False),
    sa.Column('CaseMasterID', sa.Integer(), nullable=False),
    sa.Column('EvidenceType', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('StoragePath', sa.String(length=500), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['CaseMasterID'], ['src_CaseMaster.CaseMasterID'], ),
    sa.PrimaryKeyConstraint('EvidenceID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('src_EvidenceMaster')
    op.drop_table('int_AIExtractionQueue')
    op.drop_table('int_ERMergeCandidate')
    # ### end Alembic commands ###
